#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 16 15:17:47 2019

@author: jmobrecht
"""

import numpy as np
import matplotlib.pyplot as plt
from numpy import exp
import scipy as scipy
from scipy.optimize import fmin

xData = np.arange(-10,11,1)
yData = 1.5*exp(-(xData - 0.3)**2 / 2 / 0.9**2)

# Define Model: Gaussian
def gaussian(x, a, xc, s):
    return a * exp(-(x-xc)**2 /2 /s**2)

init = [1,1,1]

def g(a, xc, s):
    return np.sum((yData - gaussian(xData, a, xc, s))**2)

xopt = scipy.optimize.fmin(g, 1, 1, 1)


plt.figure(1)
plt.plot(xData,yData,'-r.')